### ISSUE TITLE
2017 branch?

### ISSUE THREAD

**Issue by johnx7271** [microsoftarchive/OpenGAX#3]
Will 2015 branch work on 2017?
If not, porting to vs 2017?

**Comment by FabioBo** [comment]
i’ve tried to port OpenGax on VS2017, this job was very hard for me, see this branch [https://github.com/FabioBo/OpenGAX/tree/VS2017]  your help will be appreciate.
Fabio

**Comment by johnx7271** [comment]
porting done, working now for vs 2017, see my fork.

**Comment by LeonBar** [comment]
Hi, I installed GAX and GAT to visual studio 2017 pro can i found Smart Client Software Factory templates for vs 2017 ? tnx

**Comment by LeonBar** [comment]
> porting done, working now for vs 2017, see my fork.

Hi and thanks for a great work, I installed GAX and GAT to visual studio 2017 pro. 
In our project, we use Smart Client Software Factory templates?
can I found them for visual studio 2017 version ?

**Comment by johnx7271** [comment]
you can port it yourself, by referring to how I did it for the GAT project. Smart Client Software Factory is basically a gax project as the GAT project is.

**Comment by AliTai84** [comment]
> porting done, working now for vs 2017, see my fork.

Could you please send vsix file? I have struggle to build your solution in VS 2017 without any sucess.

**Comment by johnx7271** [comment]
did you build from this https://github.com/johnx7271/OpenGAX, and choose 2017 branch ?

**Comment by AliTai84** [comment]
Yes, sure

**Comment by AliTai84** [comment]
I have successfull build and installation of GAX package. But when I trying to build GAT project I recieve next error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "GenerateMenuResource" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Practices.RecipeFramework.VisualStudio.Templates.TemplateMetaData.get_ProjectFactory() in C:\Working Copy\TOOLS\OpenGAX-VS2017\GAX\Src\VisualStudio\Package\Templates\TemplateMetaData.cs:line 299
   at Microsoft.Practices.RecipeFramework.VisualStudio.Templates.TemplateMetaData..ctor(String templateFileName, CommandID command, String packageName, RegistryKey registryRoot) in C:\Working Copy\TOOLS\OpenGAX-VS2017\GAX\Src\VisualStudio\Package\Templates\TemplateMetaData.cs:line 943
   at Microsoft.Practices.RecipeFramework.VisualStudio.Build.GenerateMenuResource.CompileCTO(String& tempCTO) in C:\Working Copy\TOOLS\OpenGAX-VS2017\GAX\Src\VisualStudio\Package\Build\GenerateMenuResource.cs:line 158
   at Microsoft.Practices.RecipeFramework.VisualStudio.Build.GenerateMenuResource.Execute() in C:\Working Copy\TOOLS\OpenGAX-VS2017\GAX\Src\VisualStudio\Package\Build\GenerateMenuResource.cs:line 99
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MetaGuidancePackage			

I saw that problem related with records in regedit.

**Comment by johnx7271** [comment]
Did you install gax built b4 build gat?

**Comment by AliTai84** [comment]
Yes, I compiled vsix file from next Gax project C:\Working Copy\TOOLS\OpenGAX-VS2017\GAX\Src\VisualStudio\Package\VisualStudio.csproj firstly.
And I have successfull installation of that vsix file in VS 2017 and now I saw it in Extensions.
I gues for getting available GAX/GAT projects in New project option I have to install GAT vsix file.
